// Reminders
export const CREATE_REMINDER = "CREATE_REMINDER";
export const CREATE_REMINDER_SUCCESS = "CREATE_REMINDER_SUCCESS";
export const GET_REMINDERS_DAY = "GET_REMINDERS_DAY";
export const GET_REMINDERS_DAY_SUCCESS = "GET_REMINDERS_DAY_SUCCESS";
export const GET_ALL_REMINDERS = "GET_ALL_REMINDERS";
export const GET_ALL_REMINDERS_SUCCESS = "GET_ALL_REMINDERS_SUCCESS";
export const REMOVE_REMINDERS_BY_DAY = "REMOVE_REMINDERS_BY_DAY";
export const REMOVE_REMINDERS_BY_DAY_SUCCESS = "REMOVE_REMINDERS_BY_DAY_SUCCESS";

// Weather

export const GET_WEATHER_CITY = "GET_WEATHER_CITY ";
export const GET_WEATHER_CITY_SUCCESS = "GET_WEATHER_CITY_SUCCESS";
